<?php

	namespace app\modules\api\controllers;

	use app\models\Users;
	use yii\base\Controller;
	use yii\helpers\Json;

	class UserController extends Controller
	{
		public $data;

		public function beforeAction($action)
		{
			$this->data = JSON::decode(file_get_contents('php://input'));
			return parent::beforeAction($action); // TODO: Change the autogenerated stub
		}

		public function actionIndex()
		{
		}

		public function actionRegister()
		{
			$model = new Users();
			foreach ($this->data as $key => $value) {
				$model->{$key} = $value;
			}
			$model->registration_date = time();
			$model->generateToken();
			$model->setPassword($model->pass);
			if ($model->save()) {
				$this->sendConfirmMail($model->token, $model->email, $model->fio);
			}
		}

		public function sendConfirmMail($token, $email, $fio)
		{

		}
	}