<?php

	namespace app\modules\api\controllers;

	use app\models\Users;
	use Yii;
	use yii\base\Controller;
	use yii\helpers\Json;
	use yii\web\Response;

	class UserController extends Controller
	{
		public $data;

		public function beforeAction($action)
		{
			Yii::$app->response->format = Response::FORMAT_JSON;

			$this->data = JSON::decode(file_get_contents('php://input'));
			return parent::beforeAction($action); // TODO: Change the autogenerated stub
		}

		public function actionIndex()
		{
		}

		public function actionRegister()
		{
			$model = new Users();
			foreach ($this->data as $key => $value) {
				$model->{$key} = $value;
			}
			$model->registration_date = time();
			$model->generateToken();
			$model->setPassword($model->pass);
			if ($model->save()) {
				$model->sendConfirmMail($model->token, $model->email, $model->fio);
			} else {
				$errors = [];
				foreach ($model->errors as $error) {
					$errors[] = $error[0];
				}
				return Json::encode($errors);
			}
			return true;
		}

		public function actionActivate()
		{
			$email = Yii::$app->getRequest()->getQueryParam('email');
			$token = Yii::$app->getRequest()->getQueryParam('token');
			$user = Users::find()->where(['email' => $email, 'token' => $token, 'status' => 0])->one();
			if ($user) {
				$user->status = 1;
				$user->save();
				return true;
			} else {
				return false;
			}
		}
	}